[package]
name = "tailr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.1", features = ["derive"] }

[dev-dependencies]
rand = "0.8"
predicates = "3.0"
assert_cmd = "2.0"